name = "Mypackage"
uuid = "dee63474-e0a5-4112-864c-9ec00896d81f"
authors = ["JunyaIto <ito.23571113@gmail.com>"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
LinearAlgebra = "1.11.0"
